# Generated by Django 3.1.4 on 2020-12-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20201215_0803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Register',
        ),
    ]
