# Generated by Django 3.1.4 on 2020-12-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20201215_0940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
